# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.25.7"

package:
  name: "lightbug_http"
  version: 0.25.7

source:
  - path: ../lightbug_http
  - path: ../LICENSE

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - pixi run mojo package . -o ${PREFIX}/lib/mojo/lightbug_http.mojopkg

requirements:
  run:
    - max >=0.25.7,<0.25.8

about:
  homepage: https://github.com/saviorand/lightbug_http
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo
  repository: https://github.com/saviorand/lightbug_http
