# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.26.1.0"

package:
  name: "lightbug_http"
  version: 0.26.1.0

source:
  - path: ../lightbug_http
  - path: ../LICENSE

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - pixi run mojo package . -o ${PREFIX}/lib/mojo/lightbug_http.mojopkg

requirements:
  run:
    - max >=0.26.1.0,<0.26.2.0
    - small_time >=26.1.0,<26.2.0

about:
  homepage: https://github.com/saviorand/lightbug_http
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo
  repository: https://github.com/saviorand/lightbug_http
