[project]
authors = ["saviorand"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community"]
description = "Simple and fast HTTP framework for Mojo!"
name = "lightbug_http"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.4"

[tasks]
build = { cmd = "rattler-build build --recipe recipes -c https://conda.modular.com/max -c conda-forge --skip-existing=all", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }
test = { cmd = "magic run mojo run_tests.mojo" }
bench = { cmd = "magic run mojo bench.mojo" }
bench_server = { cmd = "magic run mojo build bench_server.mojo && ./bench_server ; rm bench_server" }

[dependencies]
max = ">=24.5.0,<25"
gojo = "0.1.9"
small_time = "0.1.3"