name: Branch workflow

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  package:
    uses: ./.github/workflows/package.yml
